[package]
name = "crc64"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["lib", "cdylib"]

[dependencies]
phper = "0.11.0"
rolling-dual-crc = { version = "0.1.0", features = ["fast"] }

[dev-dependencies]
phper-test = "0.11.0"